name: "Publish resume to gh-pages"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and build
        run: |
          npm install --dev
          npm run build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
